# Generated by Django 5.2.6 on 2026-02-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image_path', models.CharField(max_length=255)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
