services:
  - type: web
    name: ai-helmet-detector
    env: docker
    plan: free
    region: singapore
    branch: main
    dockerContext: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: PORT
        value: "10000"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
